site_name: Kori Hanes - DevSecOps Portfolio
site_description: DevSecOps & GitOps Portfolio
site_url: https://koriwayne.com
repo_url: https://github.com/KurhyWns/koriwayne.com
repo_name: KurhyWns/koriwayne.com

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Projects:
    - Homelab Project: projects/homelab/index.md
    - Shared Pipelines:
      - Overview: shared-pipelines/index.md
      - Secrets Detection:
        - TruffleHog: shared-pipelines/secrets-detection/trufflehog.md
        - GitLeaks: shared-pipelines/secrets-detection/gitleaks.md
  - Documentation:
    - Gitea: gitea/index.md
    - MetalLB: metallb/index.md
    - ArgoCD: argocd/index.md
  - Development:
    - Branching Strategy: branching-strategy/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
