---
site_name: Kori Hanes - DevSecOps & GitOps Pipelines
site_description: DevSecOps & GitOps Pipelines
site_url: https://koriwayne.com
repo_url: https://github.com/KurhyWns/koriwayne.com
repo_name: KurhyWns/koriwayne.com

extra_css:
  - assets/css/extra.css

theme:
  name: material
  palette:
    # Dark theme
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KurhyWns

copyright: |
  <a href="https://koriwayne.com">koriwayne.com</a> |
  <a href="https://homelab.koriwayne.com">homelab.koriwayne.com</a>

nav:
  - Home: index.md
  - Projects:
      - Shared Pipelines:
          - Overview: shared-pipelines/index.md
          - Secrets Detection:
              - TruffleHog: shared-pipelines/secrets-detection/trufflehog.md
              - GitLeaks: shared-pipelines/secrets-detection/gitleaks.md
      - Linting:
          - YAML Lint: shared-pipelines/linting/yaml-lint.md
      - Security:
          - Trivy: shared-pipelines/security/trivy.md
  - Development:
      - Branching Strategy: branching-strategy/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
