site_name: Kori Hanes - Projects
site_description: Programming Projects Portfolio
site_url: https://koriwayne.com
repo_url: https://github.com/KurhyWns/static_site_test
repo_name: KurhyWns/static_site_test

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Projects:
    - Homelab Project: projects/homelab/index.md
  - Documentation:
    - Gitea: gitea/index.md
    - MetalLB: metallb/index.md
    - ArgoCD: argocd/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
