name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secrets-detection:
    uses: KurhyWns/shared-pipeline/.github/workflows/secrets-detection.yml@main
    with:
      scan-paths: '.'
      fail-on-secrets: 'true'
